name: Zip Files

on:
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=$(date +'%Y%m%dT_%H_%M_%S')" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW 
        
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: sitka-packager/ 
          dest: sitka-packager_${{NOW}}.zip
          
      - uses: actions/upload-artifact@v1
        with:
           name: my-artifact
           path: ${{ github.workspace }}/result1.zip
      
