name: Zip Files

on:
  workflow_dispatch:

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - name: Set current date as env variable
        run: echo "NOW=sitka-packager-$(date +'%Y%m%dT_%H_%M_%S').zip" >> $GITHUB_ENV
      - name: Echo current date
        run: echo $NOW 

      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: sitka-packager/ 
          dest: ${{env.NOW}}

      - name: Upload a file to Google Drive
        uses: adityak74/google-drive-upload-git-action@main
        with:
           filename: ${{ github.workspace }}/${{env.NOW}}
           credentials: ${{ secrets.SITKA_GDRIVE }}
           folderId: "1eIb837AErqhjWhC0BJqjRKeLAwhrErTG"
           
      # - uses: actions/upload-artifact@v1
      #  with:
      #     name: my-artifact
      #     path: ${{ github.workspace }}/${{env.NOW}}
      
