name: Zip Files

on:
  release:
    types: [published]

jobs:
  zip-files:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: vimtor/action-zip@v1
        with:
          files: sitka-packager/ 
          dest: result1.zip
          
      - uses: actions/upload-artifact@v1
        with:
           name: my-artifact
           path: ${{ github.workspace }}/result1.zip
      
